### ISSUE TITLE
travisify

### ISSUE THREAD

**Issue by tischi** [tischi/imagej-cluster#4]
@imagejan
You are probably very busy?!
But if you have some time it would super very nice to also add this repo to scijava maven.

**Comment by tischi** [comment]
@imagejan 
I tried `release-version.sh` and got below error. Any ideas?
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project imagej-cluster: You don't have a SNAPSHOT project in the reactor projects list. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[master 59adaa5] Bump to next development cycle
 29 files changed, 788 insertions(+), 25 deletions(-)
 create mode 100644 LICENSE.txt
../scijava-scripts/release-version.sh: line 220: release.properties: No such file or directory
```

**Comment by imagejan** [comment]
> `on project imagej-cluster: You don't have a SNAPSHOT project in the reactor projects list. -> [Help 1]`

I guess you should fix the typo here:

https://github.com/tischi/imagej-cluster/blob/a6e75aae5bb457e1f8c25406b9c8230cd784749b/pom.xml#L13

.. as the keyword for snapshot versions is `SNAPSHOT`, not `SNAPSHPOT` 😁

**Comment by tischi** [comment]
🦅 👁️ ❤️

**Comment by tischi** [comment]
@imagejan 
This is a bit weird as it seems to have pushed the SNAPSHOT versions:
https://maven.scijava.org/#nexus-search;quick~imagej-cluster
I will try again with the current one.

**Comment by tischi** [comment]
Again it pushed the SNAPSHOT: https://maven.scijava.org/#nexus-search;quick~imagej-cluster
@imagejan : Can you 🦅 👁️ another typo maybe?

**Comment by imagejan** [comment]
It seems that the release tags were successfully created, but the [release *build*](https://travis-ci.com/github/tischi/imagej-cluster/builds/202654003) failed to run.

@tischi comparing the POM of [`scijava-common`](https://github.com/scijava/scijava-common/blob/80d0a38fc9e9c1d85c3a5602cddedf6cd10984a7/pom.xml#L142-L143):

```
		<connection>scm:git:git://github.com/scijava/scijava-common</connection>
		<developerConnection>scm:git:git@github.com:scijava/scijava-common</developerConnection>
```

with the corresponding lines of your POM:

https://github.com/tischi/imagej-cluster/blob/921856e0153b90f7177dad9513c3703d08df1935/pom.xml#L58-L59

... your `developerConnection` tag might be faulty. Can you try replacing the slash following `github.com` by a colon?

```
<developerConnection>scm:git:git@github.com:tischi/imagej-cluster</developerConnection>
```

**Comment by tischi** [comment]
This did the job!
Thanks **a lot** again!
Could we remove the SNAPSHOT versions from scijava.maven?

**Comment by tischi** [comment]
...also, I never paid attention to this, but is it normal that it also uploads the next SNAPSHOT?
Does not seem to make sense to me...
https://maven.scijava.org/#nexus-search;quick~imagej-cluster

**Comment by imagejan** [comment]
@tischi it's normal that `SNAPSHOT` versions get uploaded to the *Snapshots* maven repository, and release versions get uploaded to *Releases* (see the dropdown for the bottom-left panel in your link).

So 0.6.3-SNAPSH***P***OT got uploaded as a "release" version obviously. If you ask @ctrueden or @hinerm, they might be able to remove it.

**Comment by hinerm** [comment]
>So 0.6.3-SNAPSHPOT got uploaded as a "release" version obviously. If you ask @ctrueden or @hinerm, they might be able to remove it.

removed. Thanks @imagejan!

**Comment by tischi** [comment]
Thanks a lot @hinerm, @imagejan and @ctrueden!
